### ISSUE TITLE
Undefined reference Errors while running the app

### ISSUE THREAD

**Issue by ashokbugude** [noritsuna/OpenCLCLGenerator_Sample#1]
Information:Gradle tasks [:app:assembleArm7Debug]
C:\Users\H242018\AppData\Local\Android\sdk\ndk-bundle\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64\arm-linux-androideabi\bin\ld.exe
Error:error: cannot find -lOpenCL
C:\Users\H242018\Downloads\OpenCLCLGenerator_Sample-master\OpenCLCLGenerator_Sample-master\app\src\main\jni\openclsample-jni.c
Error:(40) undefined reference to 'clGetPlatformIDs'
Error:(41) undefined reference to 'clGetDeviceIDs'
Error:(44) undefined reference to 'clCreateContext'
Error:(47) undefined reference to 'clCreateCommandQueue'
Error:(50) undefined reference to 'clCreateBuffer'
Error:(53) undefined reference to 'clCreateProgramWithSource'
Error:(57) undefined reference to 'clBuildProgram'
Error:(60) undefined reference to 'clCreateKernel'
Error:(63) undefined reference to 'clSetKernelArg'
Error:(66) undefined reference to 'clEnqueueTask'
Error:(69) undefined reference to 'clEnqueueReadBuffer'
Error:(77) undefined reference to 'clFlush'
Error:(78) undefined reference to 'clFinish'
Error:(79) undefined reference to 'clReleaseKernel'
Error:(80) undefined reference to 'clReleaseProgram'
Error:(81) undefined reference to 'clReleaseMemObject'
Error:(82) undefined reference to 'clReleaseCommandQueue'
Error:(83) undefined reference to 'clReleaseContext'
Error:error: ld returned 1 exit status
Error:Execution failed for task ':app:linkOpenclsample-jniArmeabi-v7aDebugSharedLibrary'.
> A build operation failed.
      Linker failed while linking libopenclsample-jni.so.
  See the complete log at: file:///C:/Users/H242018/Downloads/OpenCLCLGenerator_Sample-master/OpenCLCLGenerator_Sample-master/app/build/tmp/linkOpenclsample-jniArmeabi-v7aDebugSharedLibrary/output.txt
Information:BUILD FAILED
Information:Total time: 1.578 secs
Information:21 errors
Information:0 warnings
Information:See complete output in console

**Comment by noritsuna** [comment]
Please copy from your device's OpenCL.so to SDK dir. 
Android SDK doesn't have OpenCL.so.

**Comment by ashokbugude** [comment]
Thanks for your help, the issue is resolved.
