### ISSUE TITLE
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe9 in tid 12585 after executing 

### ISSUE THREAD

**Issue by ashokbugude** [noritsuna/OpenCLCLGenerator_Sample#2]
I am able to build and run the app in my mobile.
But when I run, the app opens and closes immediately with below error

A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xe9 in tid 12585 after executing 

 /* Create Kernel Program from the source */
    program = clCreateProgramWithSource(context, 1, (const char **)&CLCL_HELLO,
                                        (const size_t *)strlen(CLCL_HELLO), &ret);

Please help me in resolving it

**Comment by noritsuna** [comment]
Please check all args & response code in line 40 - 53.

**Comment by ashokbugude** [comment]
I resolved the issue by replacing '(const size_t *)strlen(CLCL_HELLO)' with NULL in 
program = clCreateProgramWithSource(context, 1, (const char **)&CLCL_HELLO,
(const size_t *)strlen(CLCL_HELLO), &ret);
